spring.application.name=KnowtedBackend
spring.security.oauth2.client.registration.google.client-id=682046560787-fr2fppqeq4v3n0dhijipkucsffs5m23i.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173,https://knowtedfrontend-oimw-oy68n10tr-aaron-haizels-projects.vercel.app
jwt.secret=
jwt.expiration=
