spring.application.name=KnowtedBackend
spring.security.oauth2.client.registration.google.client-id=${GOOGLE-CLIENTID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE-CLIENTSECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173,https://knowtedfrontend-oimw-oy68n10tr-aaron-haizels-projects.vercel.app
jwt.secret=
jwt.expiration=
