spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=INFO

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

storage.provider=gcs
gcp.bucket.name=${GCP_BUCKET_NAME}

#logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE